name: CI
on: [ pull_request, push, workflow_dispatch ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-my-keyboard:
    name: Build YMD21 v2 Vial
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli@sha256:2dc05fc9f32efebd6b05c2b8676ee548358bc7e151e9dbf4dac6b6eed4513b07 

    steps:
    - name: Checkout Vial repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: recursive

    - name: Compile Firmware
      run: |
        git config --global --add safe.directory $(pwd)
        qmk compile -kb ymdk/ymd21/v2 -km vial

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ymd21-v2-vial-firmware
        path: ./*.hex
